### ISSUE TITLE
Add option to provide TDX specific configuration 

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/trustee-operator#17]
For TDX an additional configuration (sgx_default_qcnl.conf) may be required for the AS service. 

An example to patch the operator deployment is shown in the following readme 
- https://github.com/bpradipt/coco-install/blob/main/misc/kbs-operator-install/tdx.md

This issue is to track the work to integrate this additional configuration on the operator side

cc @fidencio @mythi @lmilleri

**Comment by lmilleri** [comment]
Can anyone point me to the AS code that is using the sgx_default_qcnl.conf configuration?

**Comment by mythi** [comment]
It's not in the AS code but deeper in the SGX/TDX DCAP quoteverify libs. This is the parser afaui https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/main/QuoteGeneration/qcnl/linux/qcnl_config_impl.cpp

**Comment by lmilleri** [comment]
Added configmap for overriding the  sgx_default_qcnl.conf configuration
