### ISSUE TITLE
Can't add a new secret

### ISSUE THREAD

**Issue by lmilleri** [confidential-containers/trustee-operator#36]
Steps to reproduce the issue:

1. Create a new k8s secret: `kubectl create secret generic super-secret --from-literal key=hello -n kbs-operator-system`
2. Update KbsConfig CRD by adding the following item:

```
kbsSecretResources:
  - super-secret

```
Result:
The trustee deployment is not updated, hence the new secret is not mounted into trustee file system

**Comment by bpradipt** [comment]
Closed via https://github.com/confidential-containers/trustee-operator/pull/37
